version: "3.8"

services:
  app:
    build: .
    container_name: courses_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/courses
      - REDIS_URL=redis://cache:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: courses_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: courses_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
